backend:
  name: git-gateway
  branch: main

logo_url: "https://posicionadas.com.br/assets/posicionadas-logo.png"
site_url: "https://posicionadas.com.br"

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Artigos do Blog"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo (aparece na lista do blog)", name: "excerpt", widget: "text" }
      - { label: "Texto do artigo", name: "body", widget: "markdown" }
